### ISSUE TITLE
make a better logo

### ISSUE THREAD

**Issue by aditeyaS** [aditeyaS/peoples-choice#1]
The logo I created is very bad

**Comment by Alekhya-Dharam** [comment]
I want to work on this issue. can u pls assign this to me??

**Comment by aditeyaS** [comment]
Sure. Thanks for that.

**Comment by Alekhya-Dharam** [comment]
> Sure. Thanks for that.

Should i add logo on home page or should i change logo on TMDB page??

**Comment by aditeyaS** [comment]
Didn't quite get you, what do you mean by TMDB page?
The logo is present in assets/favicon.png which is currently being as the website icon and on README.md. If you want to add it to the webpage, feel free to do so.

**Comment by aditeyaS** [comment]
The logo I wanted to change was assets/favicon.png, but what you did was good as well. So I won't be closing the issue.

**Comment by pankaj-2503** [comment]
Hey aditeyaS may I  create the logo for  People's choice website  . Explain what you require specifically so that I can work on that . Aslo please assign this to me so that I can work on that with huge motivation ,thanks.

**Comment by pankaj-2503** [comment]
Do you want to change the favicon  for this project .
