### ISSUE TITLE
Using a framework

### ISSUE THREAD

**Issue by airone01** [aditeyaS/peoples-choice#12]
Hi 👋

Because of the way the TMDB api works, it requires some API usage to be able to fetch the correct movie name and cover art.
Using a proper framework would allow the project to expand beyond the scope of only client-sided. I would recommend the [T3 stack](https://create.t3.gg/).

This is more of a discussion than an issue.

**Comment by aditeyaS** [comment]
Hey 👋,
In short, adding APIs and all would have taken much more time. I just wanted to participate in Hacktoberfest as a maintainer, and making this just took 2 hours.
I'm short on time to make a full-stack project from scratch, but I'll be happy to contribute if you are making one.
