### ISSUE TITLE
Make a table to display all the data

### ISSUE THREAD

**Issue by aditeyaS** [aditeyaS/peoples-choice#3]

**Comment by Devanshukoli** [comment]
Hey @aditeyaS , can you elaborate more about, like how you want to display the data into table format.? any images or examples would be suffix?

**Comment by aditeyaS** [comment]
Hey @Devanshukoli I don't have an image for that. Earlier it was just displaying the top voted, then someone made it a list that shows all the votes. You can better the UI, the way you see fit.

**Comment by Devanshukoli** [comment]
Ok, Cool. Let me find some better UI for it and present it here. Then take a look at that and we can decide it later. sounds good?

**Comment by aditeyaS** [comment]
Sure. You can directly raise a PR. This repo does not have that many contributors for that data to grow. If possible, please share it with your friends.
