### ISSUE TITLE
Suggestion: Allow users to omit a favorite category

### ISSUE THREAD

**Issue by Samuel-BlankAmber** [aditeyaS/peoples-choice#55]
This could help fix #54 as the user's favourite series could be removed while retaining the rest of their data.

**Comment by BlankAmber** [comment]
Apologies, this has already been implemented. If the name (e.g. `favSeries`) is set to `null` then it already ignores the result.

**Comment by Samuel-BlankAmber** [comment]
If the name field (e.g. `favSeries`) is set to `null` then it displays a blank entry.
![image](https://github.com/aditeyaS/peoples-choice/assets/145449058/170e73e7-21ce-4623-add9-8c961482ff89)

**Comment by Samuel-BlankAmber** [comment]
Implemented in #56
