### ISSUE TITLE
Add responsive design with media-query

### ISSUE THREAD

**Issue by maztt** [aditeyaS/peoples-choice#59]
Hey everybody,

I'd like to bring up a suggestion and also implement it by introducing media queries to create a more responsive design. In this initial step, we will focus on two key improvements:

- Title Resizing: We will dynamically adjust the size of the title "PEOPLE'S CHOICE" to better fit the user's screen size.
![peopleschoice_title](https://github.com/aditeyaS/peoples-choice/assets/92126792/7da48ffa-7a2d-4e9a-8c88-3d60d4a0f852)

- Text Alignment: We will horizontally align the text with the image, slightly improving the visual layout.
![peopleschoice_align](https://github.com/aditeyaS/peoples-choice/assets/92126792/2e92758d-d1b4-4fbd-8f6f-a60da9f03fe2)

What do you say? Makes sense? I'm available to proceed with the solution, if accepted.

**Comment by aditeyaS** [comment]
Hey @maztt , do you want to work on this issue?

**Comment by maztt** [comment]
Hey @aditeyaS, yes! Thanks!
