### ISSUE TITLE
TR animation on all

### ISSUE THREAD

**Issue by aditeyaS** [aditeyaS/peoples-choice#76]
Currently, the table row animation only works on Anime, but it should work for all 3

**Comment by sushma1031** [comment]
Hello, I'd like to work on this as part of Hacktoberfest 2023. Could you please provide some more details, such as the expected behaviour?

**Comment by aditeyaS** [comment]
When you open the Anime tab and scroll, there is an animation in the table rows. But it's only on the anime table, not on the movies and TV series tabs.

**Comment by sushma1031** [comment]
Oh, I understood what you mean. Could you please assign this to me?

**Comment by aditeyaS** [comment]
done
