### ISSUE TITLE
Fix the responsiveness of top section (small-screens)

### ISSUE THREAD

**Issue by Sahilm416** [aditeyaS/peoples-choice#87]
-> Top section isn't responsive on smaller screens.
-> Overlapping on smaller screens.

-> screenshots : 

![Screenshot (45)](https://github.com/aditeyaS/peoples-choice/assets/114013781/c9d1c1db-d6bd-46ed-bc17-cebd9cb79e32)

**Comment by aditeyaS** [comment]
Hey @Sahilm416 , do you want to work on the issue?

**Comment by mohtasheem135** [comment]
Hey I want to work on this......please assign this to me

**Comment by Sahilm416** [comment]
@aditeyaS yes i would like to work on it !
