### ISSUE TITLE
Remove search results when search bar is empty

### ISSUE THREAD

**Issue by aditeyaS** [aditeyaS/peoples-choice#92]
The search results section stays when I type something in the search bar and remove everything. The search section should not be there when I clear the search bar.

**Comment by mohtasheem135** [comment]
Hey I want to work on this......please assign this to me

**Comment by aditeyaS** [comment]
Done

**Comment by mohtasheem135** [comment]
![image](https://github.com/aditeyaS/peoples-choice/assets/82079433/80fb4722-9c0e-47eb-88d9-7e2a6075c49c)

So here you dont want this "search results and No results found" section when your search bar is empty right???

**Comment by aditeyaS** [comment]
yes

**Comment by mohtasheem135** [comment]
please add the hactoberfest tag then merge it, if everything is alright
